#https://docs.projectcalico.org/v3.6/getting-started/kubernetes/

- name: Configure kubectl
  command: kubeadm init  --ignore-preflight-errors=SystemVerification --apiserver-advertise-address="{{ k8s_master_apiserver_advertise_address }}" --apiserver-cert-extra-sans="{{ k8s_master_apiserver_advertise_address }}" --node-name="{{ k8s_master_node_name }}" --pod-network-cidr="{{ k8s_master_pod_network_cidr }}"
  args: 
    creates: /etc/kubernetes/manifests/kube-apiserver.yaml

- name: Create .kube dir for {{ k8s_master_admin_user }} user
  file:
      path: "/home/{{ k8s_master_admin_user }}/.kube"
      state: directory

- name: Copy kube config to {{ k8s_master_admin_user }} home .kube dir 
  copy:
    src: /etc/kubernetes/admin.conf
    dest:  /home/{{ k8s_master_admin_user }}/.kube/config
    remote_src: yes
    owner: "{{ k8s_master_admin_user }}"
    group: "{{ k8s_master_admin_group }}"
    mode: 0660

- name: Change file ownership, group and permissions
  file:
    path: /home/{{ k8s_master_admin_user }}/tools/listPods.py
    owner: "{{ k8s_master_admin_user }}"
    group: "{{ k8s_master_admin_group }}"
    mode: '0777'

- name: Download pip
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /home/{{ k8s_master_admin_user }}/tools/get-pip.py
    mode: '0777'

- name: Install pip
  command: python /home/{{ k8s_master_admin_user }}/tools/get-pip.py

- name: Install kubernetes cli
  command: pip install kubernetes
  
# Step 2.6 from https://kubernetes.io/blog/2019/03/15/kubernetes-setup-using-ansible-and-vagrant/
- name: Generate join command
  command: kubeadm token create --print-join-command
  register: join_command

- name: Copy join command for {{ k8s_cluster_name }} cluster to local file
  become: false
  local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./{{ k8s_cluster_name }}-join-command"
